name : Hello world workflow

on :
  Push :
    branches :
      - main

jobs:
  Dilip workflow:
    runs on : ubuntu - latest
    steps :
      - name : Dilip's checkout code
        uses : actions/checkout@v3

        name : Print Greeting message
        run: echo "👋 Hello Dilip, Welcome to GitHub Actions!"
